In [1]:
z=10.8
z

10.8

In [2]:
type(z)

float

## NUMPY

In [5]:
import numpy as np

In [11]:
q= np.zeros((2,10))
q

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.eye(10) #Identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(3,2) #3 rows and 2 columns

array([[0.03547954, 0.02541819],
       [0.23066842, 0.28004906],
       [0.96401173, 0.49847202]])

In [16]:
np.random.randn(3,2) #random negative with positive integers can also be there

array([[-1.86146043,  1.26221576],
       [ 0.63975988,  0.165378  ],
       [ 0.14853627, -0.58821197]])

In [17]:
np.random.randint(34,100) #any number from 34 to 99

91

In [18]:
np.random.randint(20, 56, 100) #from 20 to 55, 100 values

array([34, 32, 31, 35, 44, 38, 27, 50, 32, 29, 48, 39, 29, 24, 41, 42, 55,
       38, 46, 35, 36, 31, 50, 24, 20, 41, 44, 20, 52, 25, 48, 48, 43, 30,
       52, 48, 45, 37, 47, 48, 52, 51, 43, 53, 27, 23, 23, 40, 28, 30, 31,
       48, 21, 35, 46, 49, 54, 45, 49, 35, 25, 30, 41, 38, 51, 38, 44, 36,
       54, 21, 35, 25, 32, 20, 20, 26, 43, 27, 40, 31, 20, 51, 37, 33, 51,
       25, 22, 42, 47, 36, 45, 39, 24, 32, 38, 32, 49, 55, 38, 25])

In [20]:
sa=np.arange(30) #from 0 to 29 will be printed
sa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
sa[9]

9

In [23]:
ra=np.random.randint(0,100,20)
ra

array([38, 68, 42, 33, 16, 82, 98, 32, 89, 30, 90, 28, 29,  9, 42, 86, 65,
       10, 11, 20])

In [24]:
sa.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [25]:
ra.min()

9

In [26]:
sa.min()

0

In [27]:
ra.argmin()

13

In [28]:
sa.dtype

dtype('int32')

In [29]:
sa[1:4]=100
sa

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])